# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo 'install DX CLI'
    wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-v5.7.6-d42cf65-linux-amd64.tar.xz | tar xJf -
    sudo ./sfdx/install
    echo 'npm update'
    sudo npm update
    
    mkdir keys
    echo 'make hub key'
    echo $(theSFtoken)
    echo $(theSFtoken) | xxd -r -ps >> keys/hub.key
    openssl rsa -in keys/hub.key -check -noout
    
    echo 'sfdx'
    sudo sfdx force:org -h