# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'test_server_key'
    
- script: |
    echo 'install DX CLI'
    wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-v5.7.6-d42cf65-linux-amd64.tar.xz | tar xJf -
    sudo ./sfdx/install
    echo 'npm update'
    sudo npm update
     
    echo 'secure file path'     
    echo $env:DOWNLOADSECUREFILE_SECUREFILEPATH
    
    echo 'sfdx'
    sudo sfdx force:org -h  

  displayName: 'Install Salesforce Envrironment'

- script:  | 
   sfdx force:auth:jwt:grant --clientid 3MVG9YDQS5WtC11p3YwwrQRFrZNWVj3tY5Kl7Ur9Hc.V2MkjTwUCwXkucLtMhQqScu5qOh9oSjJQVF_.hFhP4 --jwtkeyfile$env:DOWNLOADSECUREFILE_SECUREFILEPATH --username aurelien.pedron@sira.nsw.gov.au.siracicdtest --setdefaultdevhubusername -a hub  
 
   
- task: ShellScript@1
  inputs:
    scriptPath: ./deployPackage.sh

  displayName: 'Deploy package to SF'   